uploads = []
generated = []

[[outputs]]
id = "61GBjJdCB_EcihSlyhn0b"
uri = "file://attached_assets/stock_images/african_students_white_uniform_1.jpg"
type = "image"
title = "African students white school uniform classroom happy studying"

[[outputs]]
id = "2RrLZczVXT2t20aJSgVut"
uri = "file://attached_assets/stock_images/african_students_white_uniform_2.jpg"
type = "image"
title = "African students white school uniform classroom happy studying"

[[outputs]]
id = "LxXUrR86hziLBqqkWKEsA"
uri = "file://attached_assets/stock_images/african_students_white_uniform_3.jpg"
type = "image"
title = "African students white school uniform classroom happy studying"

[[outputs]]
id = "xWyg7UrX0xrq8rI1syqFG"
uri = "file://attached_assets/stock_images/africa_white_uniform_bright_1.jpg"
type = "image"
title = "African students white school uniform smiling bright classroom sunlight happy learning"

[[outputs]]
id = "9SQKDX7qCsUYLOlnuB_L-"
uri = "file://attached_assets/stock_images/africa_white_uniform_bright_2.jpg"
type = "image"
title = "African students white school uniform smiling bright classroom sunlight happy learning"

[[outputs]]
id = "NoRoe6kPQ9lQyuuLqJykN"
uri = "file://attached_assets/stock_images/africa_white_uniform_bright_3.jpg"
type = "image"
title = "African students white school uniform smiling bright classroom sunlight happy learning"
